const fs = require("fs");
const path = require("path");

// Carregar .env.local manualmente
const envPath = path.join(__dirname, "../.env.local");
if (fs.existsSync(envPath)) {
  const envContent = fs.readFileSync(envPath, "utf8");
  envContent.split("\n").forEach(line => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) return;
    const index = trimmed.indexOf("=");
    if (index === -1) return;
    const key = trimmed.substring(0, index).trim();
    let val = trimmed.substring(index + 1).trim();
    // Remover aspas se houver
    if (val.startsWith('"') && val.endsWith('"')) {
      val = val.substring(1, val.length - 1);
    } else if (val.startsWith("'") && val.endsWith("'")) {
      val = val.substring(1, val.length - 1);
    }
    process.env[key] = val;
  });
}

const admin = require("firebase-admin");
const projectId = process.env.FIREBASE_PROJECT_ID || "studio-7502195980-3983c";
const clientEmail = process.env.FIREBASE_CLIENT_EMAIL;
let privateKey = process.env.FIREBASE_PRIVATE_KEY;
if (privateKey) {
  privateKey = privateKey.trim().replace(/^["']|["']$/g, "").replace(/\\n/g, "\n");
}

if (privateKey && clientEmail) {
  admin.initializeApp({
    credential: admin.credential.cert({
      projectId,
      clientEmail,
      privateKey,
    }),
  });
} else {
  admin.initializeApp({ projectId });
}

const db = admin.firestore();

async function run() {
  const usersSnapshot = await db.collection("users").limit(50).get();
  let allMedia = [];

  for (const userDoc of usersSnapshot.docs) {
    const mediaSnapshot = await db.collection("users")
      .doc(userDoc.id)
      .collection("mediaGallery")
      .orderBy("createdAt", "desc")
      .limit(3)
      .get();
    
    mediaSnapshot.forEach(doc => {
      allMedia.push({
        id: doc.id,
        path: doc.ref.path,
        userId: userDoc.id,
        ...doc.data()
      });
    });
  }

  allMedia.sort((a, b) => {
    const aTime = a.createdAt ? a.createdAt.toDate().getTime() : 0;
    const bTime = b.createdAt ? b.createdAt.toDate().getTime() : 0;
    return bTime - aTime;
  });

  console.log("=== ÚLTIMO DOCUMENTO GERADO ===");
  if (allMedia.length > 0) {
    const data = allMedia[0];
    console.log(`Document ID: ${data.id}`);
    console.log(`Path: ${data.path}`);
    console.log(`Prompt: ${data.prompt}`);
    console.log(`Generated By: ${data.generatedBy}`);
    console.log(`Source: ${data.source}`);
    console.log(`URL: ${data.url}`);
    console.log(`CreatedAt: ${data.createdAt ? data.createdAt.toDate().toISOString() : "null"}`);
  } else {
    console.log("Nenhum documento encontrado.");
  }
}

run().catch(console.error);
